// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Cache struct {
	Key      string         `json:"key"`
	Value    sql.NullString `json:"value"`
	Datetime sql.NullTime   `json:"datetime"`
}

type Draft struct {
	ID          int64          `json:"id"`
	Pagepath    sql.NullString `json:"pagepath"`
	Revision    sql.NullString `json:"revision"`
	AuthorEmail sql.NullString `json:"author_email"`
	Content     sql.NullString `json:"content"`
	CursorLine  sql.NullInt64  `json:"cursor_line"`
	CursorCh    sql.NullInt64  `json:"cursor_ch"`
	Datetime    sql.NullTime   `json:"datetime"`
}

type Preference struct {
	Name  string         `json:"name"`
	Value sql.NullString `json:"value"`
}

type User struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	PasswordHash   sql.NullString `json:"password_hash"`
	FirstSeen      sql.NullTime   `json:"first_seen"`
	LastSeen       sql.NullTime   `json:"last_seen"`
	IsApproved     sql.NullBool   `json:"is_approved"`
	IsAdmin        sql.NullBool   `json:"is_admin"`
	EmailConfirmed sql.NullBool   `json:"email_confirmed"`
	AllowRead      sql.NullBool   `json:"allow_read"`
	AllowWrite     sql.NullBool   `json:"allow_write"`
	AllowUpload    sql.NullBool   `json:"allow_upload"`
}
